### ISSUE TITLE
process_map()

### ISSUE THREAD

**Issue by Nipi** [gertjanssenswillen/processmapR#8] opened 2017-12-18 13:35 UTC
Hi Gert,

as you have already intended, I am using bupaR for a project. I noted some incongruences when I use the process_map() function and the precedence_matrix(type = "absolute") function: it seems that the arcs in process_map doesn't fit well the same information showed by precedence_matrix.

Is it possible?

Thanks

**Comment by gertjanssenswillen** [comment] 2017-12-21 12:30
They should be the same, but I'm checking it. Is it only the arcs, or the nodes also?

**Comment by gertjanssenswillen** [comment] 2017-12-21 12:39
Should be fixed now. The problem is when multiple activities happen at exactly the same timestamp. Both functions ordered these differently. Currently both will order them alphabetically in such a case.

**Closed by gertjanssenswillen** 2017-12-21 12:39 UTC
Labels: bug

**Comment by Nipi** [comment] 2017-12-22 13:47
Hi Gert,

I tested the fixed function and the results are coincident between process_map e precedence_matrix.

But there is an other issue: these results differ from the same information showed by the function start_activities(level = "activity").

Probably, the ordening criterion could be based on the activity_instances_id (I know that there is a function named simple_eventlog that hasn't this information, but sometimes is very import to know if a process start with activity B or A also if the strating day is the same).

Thanks for all you effort on bupaR: it is a very useful and rich package. I really thank you.
